# Generated by Django 4.2.11 on 2024-03-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='musicDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=255)),
                ('UID', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('showUnit', models.CharField(max_length=255)),
                ('descriptionFilterHtml', models.TextField()),
                ('discountInfo', models.TextField()),
                ('imageURL', models.URLField()),
                ('masterUnit', models.CharField(max_length=255)),
                ('subUnit', models.CharField(max_length=255)),
                ('supportUnit', models.CharField(max_length=255)),
                ('otherUnit', models.CharField(max_length=255)),
                ('webSales', models.URLField()),
                ('sourceWebPromote', models.URLField()),
                ('comment', models.TextField()),
                ('editModifyDate', models.DateTimeField()),
                ('sourceWebName', models.CharField(max_length=255)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('hitRate', models.IntegerField()),
                ('showinfo', models.TextField()),
                ('time', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('locationName', models.CharField(max_length=255)),
                ('onSales', models.BooleanField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('price', models.TextField()),
                ('endTime', models.DateTimeField()),
            ],
        ),
    ]
