# Generated by Django 4.2.11 on 2024-03-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.TextField()),
                ('UID', models.TextField()),
                ('titil', models.TextField()),
                ('category', models.TextField()),
                ('showUnit', models.TextField()),
                ('descriptionFilterHtml', models.TextField()),
                ('discountInfo', models.TextField()),
                ('imageURL', models.TextField()),
                ('masterUnit', models.TextField()),
                ('subUnit', models.TextField()),
                ('supportUnit', models.TextField()),
                ('otherUnit', models.TextField()),
                ('webSales', models.TextField()),
                ('sourceWebPromote', models.TextField()),
                ('comment', models.TextField()),
                ('editModifyDate', models.TextField()),
                ('sourceWebName', models.TextField()),
                ('startDate', models.TextField()),
                ('endDate', models.TextField()),
                ('hitRate', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TextField()),
                ('location', models.TextField()),
                ('locationName', models.TextField()),
                ('onSales', models.TextField()),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
                ('Price', models.TextField()),
                ('endTime', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='musicDetails',
        ),
    ]
